import { Figtree, Urbanist } from "next/font/google";
import "./globals.css";

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fametonic Open",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figTree.variable} ${urbanist.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
